function [alg_selector] = create_IOQ_alg_selector(...
    inv_gpu_range, ...
    inv_block_range, ...
    inv_cpu_range, ...
    iter_gpu_range)

    alg_selector.is_inv_gpu   = @(nv) nv >= inv_gpu_range(1)   && nv <= inv_gpu_range(2);
	alg_selector.is_inv_block = @(nv) nv >= inv_block_range(1) && nv <= inv_block_range(2);
	alg_selector.is_inv_cpu   = @(nv) nv >= inv_cpu_range(1)   && nv <= inv_cpu_range(2);
	alg_selector.is_iter_gpu  = @(nv) nv >= iter_gpu_range(1)  && nv <= iter_gpu_range(2);
end

